### ISSUE TITLE
Dark mode inplementation

### ISSUE THREAD

**Issue by SomoneVR** [Lewinator56/StormLoader#10]
Light mode is not that great but i don't think it would take much time

**Comment by Lewinator56** [comment]
I'll add this as a feature request, im actually working on a few additions right now, dark mode is on the list already, but i need to refactor a few things to make it work properly. I have previously started adding it, then stopped due to some inconsistencies with legacy code. It will take time to add, rather than a dark mode, I may well add a theme system to allow users to change their primary, secondary, accent and text colours.

**Comment by SomoneVR** [comment]
Ok, Thanks!

**Comment by Lewinator56** [comment]
I'm re-opening this as a reminder to do it

**Comment by SomoneVR** [comment]
Alright

**Comment by Lewinator56** [comment]
Theming support should be coming in v1.1, if not on release quite soon after

**Comment by Lewinator56** [comment]
Theme support added as of commit 9af0887d9620403b4723226d3a4ba7b1b428a201
