### ISSUE TITLE
issue when downloading and deleting mods. - install_info xml writing issue

### ISSUE THREAD

**Issue by CFVUT** [Lewinator56/StormLoader#7]
So I keep getting this error 

there is an unclosed literal string. line 210, position 56. 

I keep getting it when I 

1 - install mods
2 - turn off mods
3 - turn on mods
4 - delete mod
5 - start it (sometimes)

I dont know what to do so I just came here.

**Comment by Lewinator56** [comment]
Head over to your stormworks install directory then find and delete the file 'stormloader_install_info.xml', restart stormloader then re-check all the mods (they will still have a green tick though, but need re-installing to rebuild the install file)

I'm going to leave this open because this is occuring more than I'd like.

**Comment by CFVUT** [comment]
ay that worked as far as i can see. atleast its not crashing every time i did something

**Comment by Lewinator56** [comment]
this is a common bug, Im working on a fix, I'll leave this open as a reminder

**Comment by Lewinator56** [comment]
Fixed as of v1.1 (WIP release)
